device_name: "SUCOFLEX 550 (11 meters assembly)"
device_short_id: "Cable_11m"

# Настройки для универсального ридера, специфичные для файлов этого кабеля
reader_settings:
  data_start_marker: "DATA"      # Ищем маркер "DATA"
  delimiter: ","                # Разделитель колонок - запятая
  use_columns: [0, 1, 2, 3]     # Берем 0 (Частота) и 1,2,3 (три трассы измерений)
  nan_values: [-893.01029995664] # Технический маркер пустых трасс

# Файлы измерений (Движок или класс склеит их по частоте автоматически)
measurement_files:
  system1_baseline: # Опора (Ген -> короткий кабель -> приемник)
    - "raw_data/sys1_01_1MHz.csv"
    - "raw_data/sys1_1_30MHz.csv"
  system2_with_cable: # Тракт (Добавили этот длинный кабель)
    - "raw_data/sys2_01_1MHz.csv"
    - "raw_data/sys2_1_30MHz.csv"
